### ISSUE TITLE
cooperation

### ISSUE THREAD

**Issue by silverbucket** [e14n/webfinger#15]
hi evan, we're both on the webfinger list, and im currently working on a project called sockethub, i think we can use the same webfinger client for our needs, and I'm happy to use this one. I wrote one a few months back, but it's likely incomplete, anyway feel free to grab anything from there that might help you make progress with your library.

http://guthub.com/silverbucket/avatar.js

demo here:
http://silverbucket.github.com/avatar.js/

cheers!
Nick

**Comment by evanp** [comment]
Great, thanks! I'll review and give it a try.

This is the codebase that's used for `webfinger` in npm.

**Comment by silverbucket** [comment]
cool, we should also keep our projects in mind for any ways we can join forces with sockethub and pump.io; whether through shared libraries or whatever seems practical.
